spring:
  application:
    name: beneficiary

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/beneficiary_db?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092

ataya:
  app:
    jwt:
      secret: X5afgOqtzZoFc5tICYqYonjFKAONEhg1zaWl5ouVTyAYKHD7UPl61cMrOZMCbXo4Ya7hGPszCUt416yBUG5oxBbASz6gaBmjzAzUTkyjOIMOhmV65w8YKcXDZnAk7sTSyFsETPLvhAbulf9UuVROaapSUyGsoRzJagjvBDVWsdnQNaZjIRwBpWxWyxqSKcE5G6hKlYAr4PTSS8ufZK98rHNkqWvzlYbH7PKFO0X3RtK5ZTG2m32hNycfUAL0hN6n
      expiration:
        hours: 24

  beneficiary:
    inventory-service:
      url: http://localhost:8092/service-communication
    company-service:
      url: http://localhost:8091/service-communication

server:
    port: 8094

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html