spring:
  application:
    name: contributor
  data:
    mongodb:
      uri: mongodb://admin:admin@mongo:27017/contributor_db?authSource=admin
  kafka:
    bootstrap-servers: kafka:9092


ataya:
  app:
    jwt:
      secret: DAIhuV2oMpqtTm3zdFW2wkfM7Ibh4jVYCh7zWAK5ql0mynhl2zbTHs2YBGm4VLNdm1gQKtbjGZooU1MkhNhl8Wgmidw9vYyI6VdA60eOuw2pKn65Vdn6mE7syreGuRQFXOrLDqTlU8nFqTH4k29f4QmtWCrl3qgrd76mvjITj24UC7BcXGWiyzH54qBUCvV500ZSeYRBQO3r0NRta3Ka9JofbLC9fCJ16soFqFGmONdQqef5CorB7rSu6UA71Uuo
      expiration:
        hours: 24

  contributor:
    inventory-service:
      url: http://inventory:8092/service-communication
    company-service:
      url: http://company:8091/service-communication

server:
  port: 8093

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: contributor