server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    discovery:
      enabled: true

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/inventory/**, /inventory/v3/api-docs, /inventory/swagger-ui.html, /inventory/swagger-ui/**
          filters:
            - RewritePath=/inventory(?<segment>/.*), ${segment}

        - id: address
          uri: lb://address
          predicates:
            - Path=/address/**, /address/v3/api-docs, /address/swagger-ui.html, /address/swagger-ui/**
          filters:
            - RewritePath=/address(?<segment>/.*), ${segment}


        - id: company
          uri: lb://company
          predicates:
            - Path=/company/**, /company/v3/api-docs, /company/swagger-ui.html, /company/swagger-ui/**
          filters:
            - RewritePath=/company(?<segment>/.*), ${segment}

        - id: contributor
          uri: lb://contributor
          predicates:
            - Path=/contributor/**, /contributor/v3/api-docs, /contributor/swagger-ui.html, /contributor/swagger-ui/**
          filters:
            - RewritePath=/contributor(?<segment>/.*), ${segment}

        - id: swagger-ui
          uri: lb://gateway
          predicates:
            - Path=/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html

        - id: service-swagger-docs
          uri: lb://gateway
          predicates:
            - Path=/*/v3/api-docs

        - id: service-swagger-ui
          uri: lb://gateway
          predicates:
            - Path=/*/swagger-ui.html, /*/swagger-ui/**

ataya:
  app:
    jwt:
      secret: 6073418843c8d9ebbabe1674a7546c1551603d339e495e169471eb86e78a50f18ee128e865be77ce81bd09356636b71d0480abc81c0a2b5db8d7acb4f35d694e88c99aeb64ed2b521d2e2bdd1f89637b5ae7bac75484a9cc9521633604d58f1f27a3719bb0e27c4e2794656eefc49e42d00181bf3d1672a24c46b8d652a0c80e547f95e4a05cbf095a61f643aef9abe5d59b9451a95f9e709031a4609700afca25a732749c182d7f60668f4b17baf65f13e814d51d54083bdb4274b8bfefa65e7eaa4f97482952c529c4b5ab83ec8ea2f845ab8b86af689a133702cf435bd4a5a7006740386159f23cabe3adcb3844fc95d31bf90d555e3ce4e2de14cf811e5d206bd54697b9f7f06e280b4f363c553d9a28bb535922b4785eb4c2f27cd131b13331375c727f04c63903ab7c30a9a867453b19c3068998f63bdb594554970599a3bc5732d17e532403629d17f6ee579f4af429559a0aeef57eb8ac60ca9f4daff3b96bebd9b7b9c03bd2dfe775d1e85df12e3ad26e542ec92
      expiration:
        hours: 24
